name: Deploy to Apache Server

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run remote command via SSH
      uses: D3rHase/ssh-command-action@latest
      with:
        host: 192.168.1.110
        port: 22
        user: root
        private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          ssh root@192.168.1.110
          cd /var/www/html
          git pull origin main
          systemctl restart apache2
