name: Deploy to Apache Server

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up SSH
      uses: MuhammadFauzaan/autoDeployTest@main
      with:
        host: 192.168.1.110
        username: root
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh root@192.168.1.110 '
          cd /var/www/html
          git pull origin main
          sudo systemctl restart apache2
        '
